# =====================================================================================
#         ┌--- ┌---
#         |    ├---     CfBot Configuration File (config.yml)
#         |    |        Bulded By SamHacker, Open Sourced with pleasure
#         └--- ┴
# =========================================================== Developed By @SamHacker =
#
#         A Discord Bot for "whiter.lnstw.xyz", a Minecraft Server's bot.

# ================================
#  ○ Bot 設定
#  檔案：main.py
# ================================

# 專案版本
# 這個版本號會顯示在機器人的狀態中，非開發人員請勿更改！
# 本配置與程式版本不同可能會導致程式崩潰！
# 如果你不知道你在做什麼，請不要更改這個設定！
version: 1.0.5

# Bot Token
# token: "yourtoken.pastethere"
# Token 請撰寫於 token.txt 檔案中，以避免洩漏

# 是否於啟動時開啟非同步協程自動檢查更新
check_update: true

# 是否啟動除錯模式
# 在除錯模式下，機器人會顯示更多的除錯訊息，並啟動引入模組的除錯模式（降低它們的除錯等級至DEBUG，預設為WARNING）
debug: true

# ================================
#  ○ 公告程式設定
#  齒輪：annou.py
# ================================

# 是否自動同步Slash指令
auto_sync: true

# 公告頻道ID
annou_channel_id: 0000000000000000000

# 管理員 Discord ID
admin_id:
  - 959977374471028779
  - 0000000000000000000

# 管理員身分組 ID

# ================================
#  ○ 公告格式設定
#  齒輪：annou.py
# ================================
#
# 你可以使用以下Placeholder：
# {self.intro} - 公告引言
# {self.content} - 公告內容（在更新公告中為更新內容，在維修公告中為維修影響，程式會自動將它轉換為無序列表）
# {self.starter} - 公告發起人（管理員）（會使用Mention）
# {self.timestamp} - 公告發布時間（會自動轉換為可讀時間）

# 以下Placeholder僅能在維修公告中使用：
# {self.reason} - 維修原因
# {self.start} - 維修開始時間
# {self.end} - 維修結束時間

# 更新公告
update_format: |
  ## 雲羽更新

  {self.intro}

  ### 更新內容
  {self.content}


  最後，祝各位 **<:gousthappy:1194802726442381312>在本服中遊玩愉快！**
  期待各位的新進度，掰掰！

  📢 雲羽生存服 管理團隊 - <@{self.starter}> 敬上
    <t:{self.timestamp}:F>

  [ ||<@&1190290928112517212>||  |  ||<@&1190291336750960773>||  |  ||<@&1190298140692185128>||  |  ||<@&1186541054514704434>||]

# 維修公告
fix_format: |
  ## 雲羽維修

  {self.intro}

  ### 維修原因
  {self.reason}

  ### 維修預計時間
  - **<a:928961403749019649:1198243923915718706> 開始**：{self.start}
  - **<a:928961427685904385:1198243930731458651> 結束**：{self.end}

  ### 維修造成影響
  {self.content}

  ### 維修狀態
  <:dangerous:1254019093900558397> 還未開始


  很抱歉打擾各位的生活了，希望各位見諒
  為了維持完美的遊戲體驗，讓我們一起共創更美好的伺服器！<a:yeees:1197923046149853195> 

  📢 雲羽生存服 管理團隊 - <@{self.starter}> 敬上

  [ ||<@&1190290928112517212>||  |  ||<@&1190291336750960773>||  |  ||<@&1190298140692185128>||  |  ||<@&1186541054514704434>||]

# ================================
#  ○ 歡迎訊息設定
#  齒輪：welcome.py
# ================================
#
# 歡迎訊息頻道ID
welcome_channel_id: 1193435796900954162

# 歡迎訊息標題
welcome_title: "🎉 歡迎加入雲羽生存服！"

# 歡迎訊息
# 你可以使用以下Placeholder：
# {member} - 加入的成員（會使用Mention）
# {member_name} - 加入的成員（不使用Mention）
# {guild} - 伺服器名稱
# {member_count} - 伺服器成員數量
# {member_id} - 加入的成員ID
# {member_created_at} - 加入的成員創建時間
# {member_joined_at} - 加入的成員加入時間
# {member_avatar} - 加入的成員頭像（會使用URL）

welcome_message: |
  歡迎%user%來到雲羽生存服
  快來看伺服器規範 <#1186330423823978609>

# ================================
#  ○ 離開訊息設定
#  齒輪：welcome.py
# ================================
#
# 離開訊息頻道ID
leave_channel_id: 1193435796900954162

# 離開訊息標題
leave_title: "👋 再見！"

# 離開訊息
# 你可以使用以下Placeholder：
# {member} - 離開的成員（會使用Mention）
# {member_name} - 離開的成員（不使用Mention）
# {guild} - 伺服器名稱
# {member_count} - 伺服器成員數量
# {member_id} - 離開的成員ID
# {member_created_at} - 離開的成員創建時間
# {member_joined_at} - 離開的成員離開時間
# {member_avatar} - 離開的成員頭像（會使用URL）
leave_message: |
  {member} 希望你玩得愉快…
  有緣再會

# ================================
#  ○ 公告頻道防多餘訊息設定
#  齒輪：auto_delete.py
# ================================
#
# 是否自動刪除公告頻道多餘訊息
# 多餘訊息：除公告訊息（更新公告與維修公告開頭）以外的訊息
auto_delete:
  enabled: true

  # 要管理的頻道
  channel_id:
    - 1192267595534053377

  # 白名單
  # 在這裡填寫白名單的角色ID，這些角色發送的訊息不會被刪除
  whitelist:
    - 0000000000000000000

  # 私訊與否
  # 是否私訊白名單成員，告知他們的訊息會被刪除，以及不要發送多餘訊息
  dm: true

  # 私訊內容
  # 你可以使用以下Placeholder：
  # {member} - 發送多餘訊息的成員（會使用Mention）
  # {member_name} - 發送多餘訊息的成員（不使用Mention）
  # {guild} - 伺服器名稱
  # {message} - 多餘訊息內容
  dm_content: |
    你好，{member}
    你的訊息在{guild}的公告頻道中被刪除了，這是因為我們希望保持公告頻道的整潔。
    如果你有任何問題，請在其他頻道中發問，謝謝！

    詳細內容：
    {message}

# ================================
#  ○ 群組事件紀錄設定
#  齒輪：dclogging.py
# ================================
#
# 是否啟用群組事件紀錄
dc_logging:
  enabled: true # 是否啟用群組事件紀錄
  enabled_for_bot: false # 是否記錄機器人的事件

  # 紀錄頻道ID
  channel_id: 1258999406179520613

  # 是否顯示在控制台
  console: true

  # 紀錄項目
  log_events:
    msg_send: true
    msg_edit: true
    msg_delete: true

    member_join: true
    member_leave: true

    member_banned: true
    member_unbanned: true

    member_muted: true
    member_unmuted: true

    member_role_add: true
    member_role_remove: true

    vc_join: true
    vc_leave: true
    vc_move: true

# ================================
#  ○ 對MCSManager相容性設定
#  齒輪：pterodactyl.py、ptersearch.py
# ================================
mcsm: # 面板是否採用 MCSManager 面板，若是請開啟此選項，以方便pterodactyl.py和ptersearch.py正確解析數據
  enabled: false # 是否啟用 MCSManager 面板

  api_url: "https://localhost:23333/api/" # MCSManager API 根目錄（面板位址），後面記得要加上"/api/"
  api_key: "f783d2f9eb924e508a49ff2981e7e1c9" # MCSManager API 金鑰，可照https://docs.baimoqilin.top/get_your_apikey 的說明取得
  daemon_id: "a0b6fe439e15424383b2cf0075efc8f3" # 守護進程ID，如"a0b6fe439e15424383b2cf0075efc8f3"
  server_id: "ff8457ab7fb848b5998fd153c53f640c" # 伺服器ID，也就是實例ID，例如"ff8457ab7fb848b5998fd153c53f640c"

# ================================
#  ○ Pterodactyl API設定
#  齒輪：pterodactyl.py
# ================================
#
# Pterodactyl API設定
pterodactyl:
  enabled: true # 是否啟用Pterodactyl API
  api_url: "https://yourpanel.com/address" # Pterodactyl API 根目錄（面板位址），若啟動mcsm不會讀取這裡的設定
  api_key: "yourapikey.pastethere" # Pterodactyl API 金鑰，若啟動mcsm不會讀取這裡的設定
  server_id: "abcdefgh" # 伺服器ID

# ================================
#  ○ Discord 綁定檢查
#  齒輪：ptersearch.py
# ================================
ptersearch:
  enabled: true # 是否啟用 Discord 綁定檢查
  db_path: "databases\\playermapping.db" # 資料庫路徑
  api_url: "https://yourpanel.com" # Pterodactyl API 根目錄（面板位址）
  api_key: "yourapikey.pastethere" # Pterodactyl API 金鑰
  server_id: "abcdefgh" # 伺服器ID

  # 自動更新任務相關設定 (Beta)
  # ㄡ請注意，設定時需確保此設定不會超過您伺服器的 API 請求限制，否則伺服器可能崩潰！
  # 請注意，千萬不要把 interval 設為 0，程式不會自行檢查這個設定是否合理，這可能會導致伺服器崩潰！
  # 請只在您知道您在做甚麼時才啟用此功能！
  upd_task:
    enabled: false # 是否啟用自動更新任務
    interval:
      seconds: 0 # 每幾秒更新一次
      minutes: 0 # 每幾分鐘更新一次
      hours: 20 # 每幾小時更新一次

# ================================
#  ○ 客服單系統
#  齒輪：tickets/...
# ================================
tickets:
  enabled: false # 是否啟用客服單系統
  remove_log_when_bot_launch: true # 機器人啟動時是否刪除客服單紀錄
  ticket_panel_id: 1327254407443775510 # 客服單面板頻道ID
  category_id: 1327254276753330196 # 客服單分類ID
  log_channel_id: 1327254390137946202 # 客服單紀錄頻道ID
  staff_role_id: # 客服人員角色ID
    - 1186541054514704434
  confirm_message_expired: 10 # 確認訊息過期時間（秒）
  allow_call_staff: true # 是否允許呼叫客服

  # 按鈕文字
  button_texts:
    new_ticket: "📝 開啟客服單" # 開啟客服單按鈕
    close_ticket: "🔒 關閉客服單" # 關閉客服單按鈕
    call_staff: "🔔 呼叫客服" # 呼叫客服按鈕
    confirm: "✅ 確認" # 確認按鈕
    cancel: "❌ 取消" # 取消按鈕

  # 訊息設定
  messages: # 訊息相關設定，暫時不提供按鈕內容、通知等的修改，因為容易造成問題
    new_ticket: "你的客服單已創建，請在下方開始說明你的需求。" # 新客服單訊息
    close_ticket: "客服單已關閉。" # 關閉客服單訊息
    error: "⚠錯誤" # 錯誤訊息
    retry: "發生了錯誤，請重新試試" # 重試訊息
    ticket_exists: "⚠你已有開啟客服單" # 已開啟客服單訊息
    success: "✅成功" # 成功訊息
    close_ticket_confirm: "確定要關閉客服單嗎？" # 關閉客服單確認訊息
    running: "執行中..." # 執行中訊息
    is_not_ticket: "此頻道不是一個客服單" # 頻道非客服單時的訊息
    no_permission: "你沒有權限這麼做" # 沒有權限時的訊息

  # 多行訊息
  multiline_messages:
    # 你可以使用以下 Placeholder：
    # {user} - 用戶名稱（不提及）
    # {user_mention} - 用戶名稱（提及）
    # {user_id} - 用戶ID
    # {channel} - 頻道名稱（不提及）
    # {channel_mention} - 頻道名稱（提及）
    # {channel_id} - 頻道ID
    # {staff_mention} - 客服人員（提及）
    welcome_ticket: |
      歡迎 {user_mention} 開啟客服單！
      請在下方開始說明你的需求。
      有任何問題，請隨時提問。

    call_staff: |
      {staff_mention} 有人呼叫客服！
      請盡快前往 {channel_mention} 處理。

  # 嵌入文字
  embed_text:
    mainmenu:
      title: "客服單"
      description: |
        歡迎使用客服單系統！
        你可以在這裡開啟新的客服單，或是關閉現有的客服單。
        如果你有任何問題，請隨時提問。

      color: 0x00ff00

    ticket_panel:
      title: "客服單"
      description: "點擊下方按鈕開啟新的客服單。"
      color: 0x00ff00

# ================================
#  ○ 自動回覆
#  齒輪：auto_reply.py
# ================================
auto_reply:
  enabled: true # 是否啟用自動回覆

  # 如果符合以下規則，就跳過自動回覆該則訊息
  ignore_rules:
    ignore_bots: true # 忽略機器人
    ignore_self: true # 忽略自己
    ignore_roles: # 忽略的身分組
      - 0000000000000000000
    ignore_users: # 忽略的用戶
      - 0000000000000000000
    ignore_channels: # 忽略的頻道
      - 0000000000000000000

  # 回覆規則設定
  rules:
    # 這是一個範例規則，你可以根據這個規則添加更多規則，如果沒有規則會自動跳過
    # 建議將重要的規則放在前面，以避免被其他規則覆蓋
    # 請注意，這裡的規則是按照順序進行的，如果有多個規則符合，將使用第一個符合的規則
    # 如果缺乏設定項，將以預設值進行處理
    # 你可以使用以下Placeholder：
    # {message} - 觸發者發送的訊息內容
    # {author} - 自動回覆觸發者名稱
    # {author_mention} - 自動回覆觸發者提及
    # {author_id} - 自動回覆觸發者ID
    # {channel} - 自動回覆觸發頻道名稱
    # {channel_mention} - 自動回覆觸發頻道提及
    # {channel_id} - 自動回覆觸發頻道ID
    # {guild} - 自動回覆觸發伺服器名稱
    # {guild_id} - 自動回覆觸發伺服器ID
    - trigger: "hello" # 觸發字串
      response: | # 回覆內容
        Hello World
      match_regex: false # 是否使用正則表達式匹配
      no_reply: false # 設為true，則不使用回覆，而是直接傳送訊息

# ================================
#  ○ 回應身分組
#  齒輪：reaction_roles.py
# ================================
reaction_roles:
  enabled: false # 是否啟用反應身分組
  role_message_id: 0000000000000000000 # 身分組訊息ID
  role_channel_id: 0000000000000000000 # 身分組訊息頻道ID
  remove_role_on_reaction_remove: true # 移除反應時是否移除身分組
  reactions: # 反應設定，使用清單模式來設定多個
    - emoji: "🎮" # 反應表情符號
      role_id: 0000000000000000000 # 身分組ID

# ================================
#  ○ 伺服器統計
#  齒輪：serverstats/serverstats.py
# ================================
serverstats:
  enabled: true # 是否啟用伺服器統計
  loop_interval: 120 # 更新間隔（秒）
  count_run_time: true # 是否計算運行時間
  auto_start: true # 是否自動啟動統計
  counters: # 統計項目
    # 你可以使用以下Placeholder：
    # {count} - 該項目計算出的結果
    member: # 與成員有關的統計
      all_members: # 所有成員數量
        enabled: true # 是否啟用
        channel_id: 1376128480458182666 # 頻道ID
        channel_name: "所有成員：{count}" # 頻道名稱

      online_members: # 在線成員數量
        enabled: true # 是否啟用
        channel_id: 1376128503027597363 # 頻道ID
        channel_name: "線上成員：{count}" # 頻道名稱

      offline_members: # 離線成員數量
        enabled: true # 是否啟用
        channel_id: 1376128569876676730 # 頻道ID
        channel_name: "離線成員：{count}" # 頻道名稱

      humans: # 人類成員數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "人類成員：{count}" # 頻道名稱

      bots: # 機器人成員數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "機器人成員：{count}" # 頻道名稱

      member_banned: # 被封鎖成員數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "被封鎖成員：{count}" # 頻道名稱

      member_no_role: # 沒有身分組成員數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "沒有身分組成員：{count}" # 頻道名稱

      member_with_role: # 有身分組成員數量
        enabled: false # 是否啟用
        roles:
          - role_id: 1190290928112517212 # 身分組ID
            channel_id: 1193435796900954162 # 頻道ID
            channel_name: "有身分組xx成員：{count}" # 頻道名稱

    guild: # 與伺服器有關的統計
      guild_booster: # 伺服器加成人員數
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "加成人數：{count}" # 頻道名稱

      guild_boost_level: # 伺服器加成等級
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "加成等級：{count}" # 頻道名稱

      channels: # 頻道數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "頻道數量：{count}" # 頻道名稱

        text_channels: # 文字頻道數量
          enabled: false # 是否啟用
          channel_id: 1193435796900954162 # 頻道ID
          channel_name: "文字頻道數量：{count}" # 頻道名稱

        annou_channels: # 公告頻道數量
          enabled: false # 是否啟用
          channel_id: 1193435796900954162 # 頻道ID
          channel_name: "公告頻道數量：{count}" # 頻道名稱

        voice_channels: # 語音頻道數量
          enabled: false # 是否啟用
          channel_id: 1193435796900954162 # 頻道ID
          channel_name: "語音頻道數量：{count}" # 頻道名稱

        forum_channels: # 論壇頻道數量
          enabled: false # 是否啟用
          channel_id: 1193435796900954162 # 頻道ID
          channel_name: "論壇頻道數量：{count}" # 頻道名稱

        stage_channels: # 舞台頻道數量
          enabled: false # 是否啟用
          channel_id: 1193435796900954162 # 頻道ID
          channel_name: "舞台頻道數量：{count}" # 頻道名稱

      roles: # 身分組數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "身分組：{count}" # 頻道名稱

      emojis: # 表情符號數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "表情符號：{count}" # 頻道名稱

      stickers: # 貼圖數量
        enabled: false # 是否啟用
        channel_id: 1193435796900954162 # 頻道ID
        channel_name: "貼圖數量：{count}" # 頻道名稱
